#!/bin/sh
set -e

RAN_MARKER=/etc/tedge/.bootstrapped

log() {
    echo "$@" >&2
}

init_tedge_data() {
    # Create data persistence folders
    # Ensure persistence of operation state across partition swaps by storing
    # information on a persisted mount
    DATA_DIR="${DATA_DIR:-/data}"
    if [ -d "$DATA_DIR" ]; then
        log "Creating tedge persistence folder under $DATA_DIR/tedge"

        if [ -d /etc/tedge-default ]; then
            log "Copying files from /etc/tedge-default to $DATA_DIR/tedge"
            cp -rp /etc/tedge-default "$DATA_DIR/tedge"
        fi

        mkdir -p "$DATA_DIR/tedge"
        mkdir -p "$DATA_DIR/tedge/log"
        mkdir -p "$DATA_DIR/tedge/agent"
        chown -Rh tedge:tedge "$DATA_DIR/tedge"

        log "Creating tedge persistence folder under $DATA_DIR/mosquitto"
        mkdir -p "$DATA_DIR/mosquitto"
        chown -Rh mosquitto:mosquitto "$DATA_DIR/mosquitto"
    fi
}

# set hostname
DEVICE_ID=
attempt=0
while [ "$attempt" -lt 30 ]; do
    DEVICE_ID="$(tedge-identity ||:)"
    if [ -n "$DEVICE_ID" ]; then
        log "Found valid DEVICE_ID"
        break
    fi
    attempt=$((attempt + 1))
    log "Waiting for tedge-identity"
    sleep 5
done

init_tedge_data

# Run bootstrapping hooks
RUN_PARTS="/usr/share/tedge-bootstrap/scripts.d"
NAME_FILTER="[0-9][0-9]_*"

_NEWLINE=$(printf '\n')
find -L "$RUN_PARTS" -type f -name "$NAME_FILTER" -perm 755 | sort -V | while IFS="$_NEWLINE" read -r file
do
    log "Executing bootstrap script: $file"
    if "$file" "$DEVICE_ID"; then
        log "bootstrap hook ($file) was successful"
    else
        log "bootstrap hook ($file) failed. Exiting..."
        exit 1
    fi
done

touch "$RAN_MARKER"
